### ISSUE TITLE
Missing / in path for ajax calls

### ISSUE THREAD

**Issue by dzikakis** [ten24/slatwall#4939]
I'm getting several path errors in the admin like :

http://dev.demo.com/Slatwallindex.cfm/api/scope/getCart/
http://dev.demo.com/Slatwallindex.cfm/api/scope/getAccount/

where the / is missing between Slatwall and Index.cfm   this is under mura.

**Comment by sumitverma** [comment]
This has been resolved now:
https://github.com/ten24/slatwall/pull/4936/files

**Comment by rmarchandTen24** [comment]
this will be fixed in the next version as soon as the github DDOS attack
subsides
 





On Thu, Oct 20, 2016 11:10 PM, dzikakis notifications@github.com
wrote:
I'm getting several path errors in the admin like :

http://dev.demo.com/Slatwallindex.cfm/api/scope/getCart/
http://dev.hayabusafight.com/Slatwallindex.cfm/api/scope/getAccount/
