### ISSUE TITLE
Image tag obstructs account information when creating a new order for existing user. 

### ISSUE THREAD

**Issue by dbarth-aca** [ten24/slatwall#5787]
When creating an order for an existing user, the Gravatar image is not displaying correctly. The Gravatar image used to display to the left of the accounts. Instead of the image, the tag for that image appears and obstructs the account information.  
![brokenavatar](https://user-images.githubusercontent.com/6394248/31188678-ef9bd0b0-a8f2-11e7-8189-a284580f5587.jpg)

**Comment by rmarchandTen24** [comment]
The fix will be 5.1.012  





On Wed, Oct 4, 2017 1:02 PM, David notifications@github.com  wrote:
When creating an order for an existing user, the Gravatar image is not
displaying correctly. The Gravatar image used to display to the left of the
accounts. Instead of the image, the tag for that image appears and obstructs the
account information.
