### ISSUE TITLE
Can't Place International Orders

### ISSUE THREAD

**Issue by brandonholmes717** [ten24/slatwall#5944]
Hi all,

Our company's website is having an issue with our international clients not being able to place orders, and this appears to be a recent issue that has creeped up as we've never had issues with this in the past. Over the last week or so we've received notices from clients in Canada, Australia, and the UK who all report getting this message when trying to place an order:

## **Shipping Method**
Unfortunately the shipping address that you have provided is not one that we ship to. Please update your shipping address and try again, or contact customer service for more information.

I'm entirely unsure why or how this error has come about and naturally I find it totally bizarre. Would anyone have any insight into what the issue may be?

Thank you in advance, hope someone can help.

– Brandon

**Comment by tdhatcher** [comment]
Are you on "stable"? There's likely fulfillment and shipping method configuration settings that is preventing this. More details how you are using it would be helpful to gain insight.

**Comment by brandonholmes717** [comment]
Where would I be able to find that information? Sorry, I'm not too experienced with Slatwall, but it seems as though these responsibilities have fallen to me at the time as we don't have a dedicated IT employee on our payroll.

**Comment by tdhatcher** [comment]
You can find the current version you are running by going to:
**Slatwall Admin > Tools > Update Slatwall**

Inspect your fulfillment & shipping methods
**Slatwall Admin > Config > Fulfillment Methods**
There you will see what methods you have available for fulfillment method (of fulfillment method type=shipping).

Fulfillment method should have at least one shipping method configured. For example, standard ground. And that shipping method should have at least one shipping rate configured. These can be manually fixed rates or if you rely on a 3rd party like FedEx or UPS which are fetched at the proper time in the order process. They can be further restricted to address zones (eg. country must be US, and/or state must be California).

If your international customers are not seeing shipping options it could either be because of the address zone restriction which is manually configured, or could be an issue with the 3rd party shipper not providing a rate for the address. In that case you need to verify that your shipper account credentials are correct and that their API is functional for your account.
