### ISSUE TITLE
Mura 7.1 Slatwall redirect

### ISSUE THREAD

**Issue by Tigerlady** [ten24/slatwall#7055]
I am trying to get Slatwall to work on a generic version of Mura with Bootstrap 4 standard template.  When I activate Slatwall to the default site I get a redirect error
This page isn’t working www.mydomain.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

Clearing cookies does not help and I cannot access the Mura admin.  

I have tried many things even deleting the entire site and starting over again. 

The redirect happens on the main site and the Mura admin however, I can get to https://www.mydomain.com/Slatwall/?slatAction=main.login&fw1pk=1 however, I can't login as I set the admin to use the super user of Mura.  

So far I am totally stuck on getting the site up and running.  

I am running on Windows IIS 10
Lucee 5.3.1.102
Mura 7.1

If I disable the plugin in the database and do an appreload I am able to get back to the admin of Mura.  I am looking for a way to fix the redirect loop issue. 

In the Mura setting.ini.cfm file I do not use site IDs and index.cfm in the urls.  In my webconfig file on the root of the site I have set it to remove the index.cfm

**Comment by damienbkx** [comment]
Hello, 

I had a similar issue with Mura when trying to enforce https://, and I think you are running into the same problem.
Some systems on Slatwall MUST use https://
The problem is the connection between your web server (IIS) and Lucee. IIS acts as a proxy that relays the request to Lucee. 
As far as HTTPS is concerned, the request from the client to IIS is in HTTPS, but then, IIS relays the request to Lucee using regular HTTP. When the request reaches the Lucee server, Lucee sees it as an HTTP request rather then an https request and initiates a redirecttion to https, bu then, the request is proxied again by IIS in http, which tiggers the next redirection, and you have a loop with the "Too many redirect" message. 
I am using the apache HTTP server (not iis), and to make it work I had to add the following header in my virtual host config : 
RequestHeader Set X-Forwarded-Proto "https"

This header tells Lucee that even though it receives an http connection from the proxy, the original connection (from the client to Apache / IIS) was made in httpS, and therefore, Lucee should consider it is https. When I did that, no more redirection and both Mura and Slatwall were rnning somootjly on https..

Hope it helps..
Damien
